# Generated by Django 6.0 on 2025-12-10 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_post_content_follow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Distillery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=150, null=True)),
                ('climate', models.CharField(blank=True, max_length=150, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('whiskey_type', models.CharField(choices=[('bourbon', 'Bourbon'), ('rye', 'Rye'), ('single_malt', 'Single Malt'), ('blended', 'Blended Whiskey'), ('scotch_single_malt', 'Scotch – Single Malt'), ('scotch_blended', 'Scotch – Blended'), ('irish', 'Irish'), ('japanese', 'Japanese'), ('canadian', 'Canadian'), ('corn', 'Corn'), ('wheat', 'Wheat Whiskey'), ('american_single_malt', 'American Single Malt'), ('other', 'Other')], max_length=50)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('proof', models.FloatField(blank=True, null=True)),
                ('is_store_pick', models.BooleanField(default=False)),
                ('store_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pick_details', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('unopened', 'Unopened'), ('opened', 'Opened'), ('finished', 'Finished')], default='unopened', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottles', to=settings.AUTH_USER_MODEL)),
                ('distillery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bottles', to='accounts.distillery')),
            ],
        ),
    ]
