# Generated by Django 6.0 on 2025-12-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_distillery_bottle'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
