# Generated by Django 6.0 on 2025-12-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_bottle_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='share_stats',
            field=models.BooleanField(default=False),
        ),
    ]
