# Generated by Django 6.0 on 2025-12-12 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_share_stats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distillery',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='distillery',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, help_text='If this distillery is a duplicate, point to the canonical record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='accounts.distillery'),
        ),
        migrations.AlterField(
            model_name='distillery',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distilleries_added', to=settings.AUTH_USER_MODEL),
        ),
    ]
