# Generated by Django 6.0 on 2025-12-15 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_distillery_options_alter_distillery_added_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distillery',
            options={'permissions': [('can_review_distillery', 'Can approve or merge distilleries')]},
        ),
        migrations.AlterField(
            model_name='distillery',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, help_text='If this distillery is a duplicate, point to the canonical distillery.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='accounts.distillery'),
        ),
    ]
