# Generated by Django 6.0 on 2025-12-15 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_distillery_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distillery',
            options={'permissions': [('can_review_distillery', 'Can review and approve distilleries')]},
        ),
    ]
