# Generated by Django 6.0 on 2025-12-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_bottlereview_finish_alter_bottlereview_nose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distilleryauditlog',
            name='notes',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
