# Generated by Django 6.0 on 2025-12-22 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_distilleryauditlog_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanonicalBottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('whiskey_type', models.CharField(choices=[('bourbon', 'Bourbon'), ('rye', 'Rye'), ('single_malt', 'Single Malt'), ('blended', 'Blended Whiskey'), ('scotch_single_malt', 'Scotch – Single Malt'), ('scotch_blended', 'Scotch – Blended'), ('irish', 'Irish'), ('japanese', 'Japanese'), ('canadian', 'Canadian'), ('corn', 'Corn'), ('wheat', 'Wheat Whiskey'), ('american_single_malt', 'American Single Malt'), ('other', 'Other')], max_length=50)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('proof', models.FloatField(blank=True, null=True)),
                ('is_store_pick', models.BooleanField(default=False)),
                ('store_name', models.CharField(blank=True, help_text='Only set if this is a store pick', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_canonical_bottles', to=settings.AUTH_USER_MODEL)),
                ('distillery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canonical_bottles', to='accounts.distillery')),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='accounts.canonicalbottle')),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='accounts_ca_name_ead2ee_idx'), models.Index(fields=['whiskey_type'], name='accounts_ca_whiskey_1d3e84_idx')],
            },
        ),
    ]
