# Generated by Django 6.0 on 2025-12-22 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_canonicalbottle'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bottlereview',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='bottlereview',
            name='bottle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.canonicalbottle'),
        ),
    ]
