# Generated by Django 6.0 on 2025-12-22 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_bottlereview_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='canonical_bottle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_bottles', to='accounts.canonicalbottle'),
        ),
    ]
