# Generated by Django 6.0 on 2025-12-23 05:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_bottle_canonical_bottle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='canonicalbottle',
            constraint=models.UniqueConstraint(fields=('name', 'distillery', 'whiskey_type', 'is_store_pick', 'store_name'), name='unique_canonical_bottle_identity'),
        ),
    ]
