# Generated by Django 6.0 on 2025-12-24 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_eventbottle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bottlereview',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.event'),
        ),
        migrations.AddField(
            model_name='bottlereview',
            name='event_bottle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.eventbottle'),
        ),
        migrations.AddConstraint(
            model_name='bottlereview',
            constraint=models.UniqueConstraint(condition=models.Q(('event_bottle__isnull', False)), fields=('reviewer', 'event_bottle'), name='one_review_per_user_per_event_bottle'),
        ),
    ]
