# Generated by Django 6.0 on 2025-12-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_bottlereview_event_bottlereview_event_bottle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='visibility',
            field=models.CharField(choices=[('friends', 'Friends Only'), ('public', 'Public')], default='friends', max_length=20),
        ),
    ]
