# Generated by Django 6.0 on 2025-12-30 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_notification_unique_notification_per_user_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='canonicalbottle',
            name='forked_from',
            field=models.ForeignKey(blank=True, help_text='Original canonical bottle this was forked from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='accounts.canonicalbottle'),
        ),
    ]
