# Generated by Django 6.0 on 2026-01-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_canonicalbottle_forked_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottlereview',
            name='final_score',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
