# Generated by Django 6.0 on 2026-06-24 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_bottlereview_final_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
