"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_dotenv(path):
    """Minimal .env loader (no dependency). Real env vars take precedence, so a
    value already set in the environment is never overwritten by the file."""
    try:
        with open(path, encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                key, _, value = line.partition("=")
                os.environ.setdefault(key.strip(), value.strip())
    except FileNotFoundError:
        pass


# Load a local .env if present. This file holds secrets and is gitignored.
_load_dotenv(BASE_DIR / ".env")

# --- Distillery web lookup ---
# Optional Gemini API fallback for the distillery review screen. When
# GEMINI_API_KEY is unset, lookups use Wikipedia only.
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "")
GEMINI_MODEL = os.environ.get("GEMINI_MODEL", "gemini-2.0-flash")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# In production, set DJANGO_SECRET_KEY in the environment. The fallback below is
# for LOCAL DEVELOPMENT ONLY and must never be used on a public server (the old
# committed value is considered compromised and has to be rotated).
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-dev-only-do-not-use-in-production-change-me",
)

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to True for local dev; set DJANGO_DEBUG=False in production.
DEBUG = os.environ.get("DJANGO_DEBUG", "True").strip().lower() != "false"

# Hosts/domains this site may serve. In production set DJANGO_ALLOWED_HOSTS to a
# comma-separated list, e.g. "example.com,www.example.com".
ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if h.strip()
]

# Origins trusted for CSRF over HTTPS (required by Django 4+ for cross-origin
# POSTs). In production set DJANGO_CSRF_TRUSTED_ORIGINS, e.g.
# "https://example.com,https://www.example.com".
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if o.strip()
]

# Railway injects the app's public domain at runtime. Trust it automatically so
# the first deploy works without having to hardcode the generated *.railway.app
# hostname in the env vars above.
_railway_domain = os.environ.get("RAILWAY_PUBLIC_DOMAIN", "").strip()
if _railway_domain:
    ALLOWED_HOSTS.append(_railway_domain)
    CSRF_TRUSTED_ORIGINS.append(f"https://{_railway_domain}")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts.apps.AccountsConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise serves static files in production; must sit right after Security.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import dj_database_url

# Reads the DATABASE_URL env var (e.g. Railway's managed Postgres). When it's
# unset — i.e. local development — this falls back to the bundled SQLite file,
# so nothing changes for local work.
DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,        # reuse connections instead of reconnecting each request
        conn_health_checks=True,
    )
}

LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# Destination for `collectstatic` in production; WhiteNoise serves from here.
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        # Compresses static files (gzip/brotli). Non-manifest variant so a
        # missing/renamed reference can't hard-fail collectstatic or page loads.
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

MEDIA_URL = '/media/'
# User uploads (avatars). On hosts with an ephemeral filesystem these are lost on
# redeploy, so point DJANGO_MEDIA_ROOT at a persistent volume (or use object
# storage) in production. Defaults to a local folder for development.
MEDIA_ROOT = os.environ.get("DJANGO_MEDIA_ROOT", "").strip() or (BASE_DIR / 'media')


# --- Security hardening --------------------------------------------------
# Applied to every environment. The HTTPS-specific settings only switch on when
# DEBUG is off (i.e. in production) so local http://localhost dev keeps working.

# Clickjacking: never allow the site to be framed by other origins.
X_FRAME_OPTIONS = "DENY"

# Cap request bodies / uploads to reduce abuse (avatars are validated separately
# in the profile form). 5 MB is generous for this app.
DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024   # 5 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024   # 5 MB

# Cache backend. Required by django-ratelimit. The default per-process
# LocMemCache is fine for a single-process deployment; switch to Redis/Memcached
# if you run multiple workers so the rate-limit counters are shared.
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "whiskey-app",
    }
}

if not DEBUG:
    # Assume the site sits behind an HTTPS-terminating proxy that forwards the
    # scheme in X-Forwarded-Proto (true for most PaaS hosts / nginx setups).
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True

    # Cookies only over HTTPS, and not readable from JavaScript.
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True

    # HTTP Strict Transport Security: tell browsers to stick to HTTPS.
    SECURE_HSTS_SECONDS = 31536000          # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Extra hardening headers.
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = "same-origin"